apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-viewer
  namespace: talhas-experiments
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::545009868178:role/talhas-secrets-viewer-irsa
